import { EndPointsTypes } from "@/common/types/routers/endPoints.types";

export const restaurantEndPoint = {
    BOOKINGS: {
        url: EndPointsTypes['RESTAURANT_BOOKING_ENDPOINT'],
        queryParams: 'Bookings',
        updateSucess: "Bookings updated successfully!",
        updateError: "Bookings update failed!",
        deleteSucess: "Bookings deleted successfully!",
        deleteError: "Bookings delete failed!",
        createSucess: 'Bookings created successfully!',
        createError: "Bookings creation failed!",
    },
    TABLES: {
        url: EndPointsTypes['RESTAURANT_TABLES_ENDPOINT'],
        queryParams: 'Tables',
        updateSucess: "Tables updated successfully!",
        updateError: "Tables update failed!",
        deleteSucess: "Tables deleted successfully!",
        deleteError: "Tables delete failed!",
        createSucess: 'Tables created successfully!',
        createError: "Tables creation failed!",
    },
    ORDER: {
        url: EndPointsTypes['RESTAURANT_ORDER_ENDPOINT'],
        queryParams: 'Order',
        updateSucess: "Order updated successfully!",
        updateError: "Order update failed!",
        deleteSucess: "Order deleted successfully!",
        deleteError: "Order delete failed!",
        createSucess: 'Order created successfully!',
        createError: "Order creation failed!",
    },
    ORDER_CONTROLLER: {
        url: EndPointsTypes['RESTAURANT_ORDER_CONTROLLER_ENDPOINT'],
        queryParams: 'Order',
        updateSucess: "Order updated successfully!",
        updateError: "Order update failed!",
        deleteSucess: "Order deleted successfully!",
        deleteError: "Order delete failed!",
        createSucess: 'Order created successfully!',
        createError: "Order creation failed!",
    },
    CLIENTS: {
        url: EndPointsTypes['RESTAURANT_CLIENT_ENDPOINT'],
        queryParams: 'Client',
        updateSucess: "Client updated successfully!",
        updateError: "Client update failed!",
        deleteSucess: "Client deleted successfully!",
        deleteError: "Client delete failed!",
        createSucess: 'Client created successfully!',
        createError: "Client creation failed!",
    },
    SECTIONS: {
        url: EndPointsTypes['RESTAURANT_SECTIONS_ENDPOINT'],
        queryParams: 'Section',
        updateSucess: "Section updated successfully!",
        updateError: "Section update failed!",
        deleteSucess: "Section deleted successfully!",
        deleteError: "Section delete failed!",
        createSucess: 'Section created successfully!',
        createError: "Section creation failed!",
    },
    MENU: {
        url: EndPointsTypes['RESTAURANT_MENU_ENDPOINT'],
        queryParams: 'Menu',
        updateSucess: "Menu updated successfully!",
        updateError: "Menu update failed!",
        deleteSucess: "Menu deleted successfully!",
        deleteError: "Menu delete failed!",
        createSucess: 'Menu created successfully!',
        createError: "Menu creation failed!",
    },
    FINISHED_TABLE: {
        url: EndPointsTypes['RESTAURANT_FINISHED_TABLES_ENDPOINT'],
        queryParams: 'Finished Table',
        updateSucess: "Finished Table updated successfully!",
        updateError: "Finished Table update failed!",
        deleteSucess: "Finished Table deleted successfully!",
        deleteError: "Finished Table delete failed!",
        createSucess: 'Finished Table created successfully!',
        createError: "Finished Table creation failed!",
    },
    REVIEWS: {
        url: EndPointsTypes['RESTAURANT_REVIEWS_ENDPOINT'],
        queryParams: 'Reviews',
        updateSucess: "Reviews updated successfully!",
        updateError: "Reviews update failed!",
        deleteSucess: "Reviews deleted successfully!",
        deleteError: "Reviews delete failed!",
        createSucess: 'Reviews created successfully!',
        createError: "Reviews creation failed!",
    },
    GIFTCARD: {
        url: EndPointsTypes['RESTAURANT_GIFTCARD_ENDPOINT'],
        queryParams: 'Giftcard',
        updateSucess: "Giftcard updated successfully!",
        updateError: "Giftcard update failed!",
        deleteSucess: "Giftcard deleted successfully!",
        deleteError: "Giftcard delete failed!",
        createSucess: 'Giftcard created successfully!',
        createError: "Giftcard creation failed!",
    },
    AUTHORIZED_DEVICES: {
        url: EndPointsTypes['AUTH_AUTHORIZED_DEVICES_ENDPOINT'],
        queryParams: 'Authorized Device',
        updateSucess: "Authorized Device updated successfully!",
        updateError: "Authorized Device update failed!",
        deleteSucess: "Authorized Device deleted successfully!",
        deleteError: "Authorized Device delete failed!",
        createSucess: 'Authorized Device created successfully!',
        createError: "Authorized Device creation failed!",
    },
    SPECIAL_DAYS: {
        url: EndPointsTypes['RESTAURANT_SPECIAL_DAYS_ENDPOINT'],
        queryParams: 'Special Day',
        updateSucess: "Special Day updated successfully!",
        updateError: "Special Day update failed!",
        deleteSucess: "Special Day deleted successfully!",
        deleteError: "Special Day delete failed!",
        createSucess: 'Special Day created successfully!',
        createError: "Special Day creation failed!",
    },
    OPEN_DAYS: {
        url: EndPointsTypes['RESTAURANT_OPEN_DAYS_ENDPOINT'],
        queryParams: 'Open Day',
        updateSucess: "Open Day updated successfully!",
        updateError: "Open Day update failed!",
        deleteSucess: "Open Day deleted successfully!",
        deleteError: "Open Day delete failed!",
        createSucess: 'Open Day created successfully!',
        createError: "Open Day creation failed!",
    },
    TIMES_OPEN: {
        url: EndPointsTypes['RESTAURANT_TIMES_OPEN_ENDPOINT'],
        queryParams: 'Times Open',
        updateSucess: "Times Open updated successfully!",
        updateError: "Times Open update failed!",
        deleteSucess: "Times Open deleted successfully!",
        deleteError: "Times Open delete failed!",
        createSucess: 'Times Open created successfully!',
        createError: "Times Open creation failed!",
    },
    PRINTERS: {
        url: EndPointsTypes['RESTAURANT_PRINTERS_ENDPOINT'],
        queryParams: 'Printer',
        updateSucess: "Printer updated successfully!",
        updateError: "Printer update failed!",
        deleteSucess: "Printer deleted successfully!",
        deleteError: "Printer delete failed!",
        createSucess: 'Printer created successfully!',
        createError: "Printer creation failed!",
    },
    TO_PRINT: {
        url: EndPointsTypes['RESTAURANT_PRINTERS_ENDPOINT'],
        queryParams: 'Printer',
        updateSucess: "Printed!",
        updateError: "Error while printing!",
        deleteSucess: "Printer deleted successfully!",
        deleteError: "Printer delete failed!",
        createSucess: "Printed!",
        createError: "Error while printing!"
    },
    MENU_SECTION: {
        url: EndPointsTypes['RESTAURANT_MENU_SECTION_ENDPOINT'],
        queryParams: 'Menu Section',
        updateSucess: "Menu Section updated successfully!",
        updateError: "Menu Section update failed!",
        deleteSucess: "Menu Section deleted successfully!",
        deleteError: "Menu Section delete failed!",
        createSucess: 'Menu Section created successfully!',
        createError: "Menu Section creation failed!",
    },
    MENU_TYPE: {
        url: EndPointsTypes['RESTAURANT_MENU_TYPES_ENDPOINT'],
        queryParams: 'Menu Type',
        updateSucess: "Menu Type updated successfully!",
        updateError: "Menu Type update failed!",
        deleteSucess: "Menu Type deleted successfully!",
        deleteError: "Menu Type delete failed!",
        createSucess: 'Menu Type created successfully!',
        createError: "Menu Type creation failed!",
    },
    MENU_ADD_ONS: {
        url: EndPointsTypes['RESTAURANT_MENU_ADD_ONS_ENDPOINT'],
        queryParams: 'Menu Add Ons',
        updateSucess: "Prerequisite updated successfully!",
        updateError: "Prerequisite update failed!",
        deleteSucess: "Prerequisite deleted successfully!",
        deleteError: "Prerequisite delete failed!",
        createSucess: 'Prerequisite created successfully!',
        createError: "Prerequisite creation failed!",
    },
    MENU_ADD_ONS_OPTIONS: {
        url: EndPointsTypes['RESTAURANT_MENU_ADD_ONS_OPTIONS_ENDPOINT'],
        queryParams: 'Menu Add Ons',
        updateSucess: "Prerequisite Option updated successfully!",
        updateError: "Prerequisite Option update failed!",
        deleteSucess: "Prerequisite Option deleted successfully!",
        deleteError: "Prerequisite Option delete failed!",
        createSucess: 'Prerequisite Option created successfully!',
        createError: "Prerequisite Option creation failed!",
    },
    MENU_TO_MAKE: {
        url: EndPointsTypes['RESTAURANT_MENU_TO_MAKE_ENDPOINT'],
        queryParams: 'Menu Add Ons',
        updateSucess: "Menu to make Option updated successfully!",
        updateError: "Menu to make Option update failed!",
        deleteSucess: "Menu to make Option deleted successfully!",
        deleteError: "Menu to make Option delete failed!",
        createSucess: 'Menu to make Option created successfully!',
        createError: "Menu to make Option creation failed!",
    },
}