import { EndPointsTypes } from "@/common/types/routers/endPoints.types";

export const restaurantEndPoint = {
    BOOKINGS: {
        url: EndPointsTypes['RESTAURANT_BOOKING_ENDPOINT'],
        queryParams: 'Bookings',
        updateSucess: "Bookings updated successfully!",
        updateError: "Bookings update failed!",
        deleteSucess: "Bookings deleted successfully!",
        deleteError: "Bookings delete failed!",
        createSucess: 'Bookings created successfully!',
        createError: "Bookings creation failed!",
    },
    TABLES: {
        url: EndPointsTypes['RESTAURANT_TABLES_ENDPOINT'],
        queryParams: 'Tables',
        updateSucess: "Tables updated successfully!",
        updateError: "Tables update failed!",
        deleteSucess: "Tables deleted successfully!",
        deleteError: "Tables delete failed!",
        createSucess: 'Tables created successfully!',
        createError: "Tables creation failed!",
    },
    ORDER: {
        url: EndPointsTypes['RESTAURANT_ORDER_ENDPOINT'],
        queryParams: 'Order',
        updateSucess: "Order updated successfully!",
        updateError: "Order update failed!",
        deleteSucess: "Order deleted successfully!",
        deleteError: "Order delete failed!",
        createSucess: 'Order created successfully!',
        createError: "Order creation failed!",
    },
    ORDER_CONTROLLER: {
        url: EndPointsTypes['RESTAURANT_ORDER_CONTROLLER_ENDPOINT'],
        queryParams: 'Order',
        updateSucess: "Order updated successfully!",
        updateError: "Order update failed!",
        deleteSucess: "Order deleted successfully!",
        deleteError: "Order delete failed!",
        createSucess: 'Order created successfully!',
        createError: "Order creation failed!",
    },
    CLIENTS: {
        url: EndPointsTypes['RESTAURANT_CLIENT_ENDPOINT'],
        queryParams: 'Client',
        updateSucess: "Client updated successfully!",
        updateError: "Client update failed!",
        deleteSucess: "Client deleted successfully!",
        deleteError: "Client delete failed!",
        createSucess: 'Client created successfully!',
        createError: "Client creation failed!",
    },
    SECTIONS: {
        url: EndPointsTypes['RESTAURANT_SECTIONS_ENDPOINT'],
        queryParams: 'Section',
        updateSucess: "Section updated successfully!",
        updateError: "Section update failed!",
        deleteSucess: "Section deleted successfully!",
        deleteError: "Section delete failed!",
        createSucess: 'Section created successfully!',
        createError: "Section creation failed!",
    },
    MENU: {
        url: EndPointsTypes['RESTAURANT_MENU_ENDPOINT'],
        queryParams: 'Menu',
        updateSucess: "Menu updated successfully!",
        updateError: "Menu update failed!",
        deleteSucess: "Menu deleted successfully!",
        deleteError: "Menu delete failed!",
        createSucess: 'Menu created successfully!',
        createError: "Menu creation failed!",
    },
    FINISHED_TABLE: {
        url: EndPointsTypes['RESTAURANT_FINISHED_TABLES_ENDPOINT'],
        queryParams: 'Finished Table',
        updateSucess: "Finished Table updated successfully!",
        updateError: "Finished Table update failed!",
        deleteSucess: "Finished Table deleted successfully!",
        deleteError: "Finished Table delete failed!",
        createSucess: 'Finished Table created successfully!',
        createError: "Finished Table creation failed!",
    },
    REVIEWS: {
        url: EndPointsTypes['RESTAURANT_REVIEWS_ENDPOINT'],
        queryParams: 'Reviews Table',
        updateSucess: "Reviews Table updated successfully!",
        updateError: "Reviews Table update failed!",
        deleteSucess: "Reviews Table deleted successfully!",
        deleteError: "Reviews Table delete failed!",
        createSucess: 'Reviews Table created successfully!',
        createError: "Reviews Table creation failed!",
    },
    GIFTCARD: {
        url: EndPointsTypes['RESTAURANT_GIFTCARD_ENDPOINT'],
        queryParams: 'Giftcard Table',
        updateSucess: "Giftcard Table updated successfully!",
        updateError: "Giftcard Table update failed!",
        deleteSucess: "Giftcard Table deleted successfully!",
        deleteError: "Giftcard Table delete failed!",
        createSucess: 'Giftcard Table created successfully!',
        createError: "Giftcard Table creation failed!",
    },
    AUTHORIZED_DEVICES: {
        url: EndPointsTypes['RESTAURANT_AUTHORIZED_DEVICES_ENDPOINT'],
        queryParams: 'Authorized Device Table',
        updateSucess: "Authorized Device Table updated successfully!",
        updateError: "Authorized Device Table update failed!",
        deleteSucess: "Authorized Device Table deleted successfully!",
        deleteError: "Authorized Device Table delete failed!",
        createSucess: 'Authorized Device Table created successfully!',
        createError: "Authorized Device Table creation failed!",
    },
    SPECIAL_DAYS: {
        url: EndPointsTypes['RESTAURANT_SPECIAL_DAYS_ENDPOINT'],
        queryParams: 'Special Day Table',
        updateSucess: "Special Day Table updated successfully!",
        updateError: "Special Day Table update failed!",
        deleteSucess: "Special Day Table deleted successfully!",
        deleteError: "Special Day Table delete failed!",
        createSucess: 'Special Day Table created successfully!',
        createError: "Special Day Table creation failed!",
    },
    OPEN_DAYS: {
        url: EndPointsTypes['RESTAURANT_OPEN_DAYS_ENDPOINT'],
        queryParams: 'Open Day Table',
        updateSucess: "Open Day Table updated successfully!",
        updateError: "Open Day Table update failed!",
        deleteSucess: "Open Day Table deleted successfully!",
        deleteError: "Open Day Table delete failed!",
        createSucess: 'Open Day Table created successfully!',
        createError: "Open Day Table creation failed!",
    },
    TIMES_OPEN: {
        url: EndPointsTypes['RESTAURANT_TIMES_OPEN_ENDPOINT'],
        queryParams: 'Times Open',
        updateSucess: "Times Open updated successfully!",
        updateError: "Times Open update failed!",
        deleteSucess: "Times Open deleted successfully!",
        deleteError: "Times Open delete failed!",
        createSucess: 'Times Open created successfully!',
        createError: "Times Open creation failed!",
    },
    PRINTERS: {
        url: EndPointsTypes['RESTAURANT_PRINTERS_ENDPOINT'],
        queryParams: 'Printer',
        updateSucess: "Printer updated successfully!",
        updateError: "Printer update failed!",
        deleteSucess: "Printer deleted successfully!",
        deleteError: "Printer delete failed!",
        createSucess: 'Printer created successfully!',
        createError: "Printer creation failed!",
    },
    MENU_SECTION: {
        url: EndPointsTypes['RESTAURANT_MENU_SECTION_ENDPOINT'],
        queryParams: 'Menu Section',
        updateSucess: "Menu Section updated successfully!",
        updateError: "Menu Section update failed!",
        deleteSucess: "Menu Section deleted successfully!",
        deleteError: "Menu Section delete failed!",
        createSucess: 'Menu Section created successfully!',
        createError: "Menu Section creation failed!",
    },
    MENU_TYPE: {
        url: EndPointsTypes['RESTAURANT_MENU_TYPES_ENDPOINT'],
        queryParams: 'Menu Type',
        updateSucess: "Menu Type updated successfully!",
        updateError: "Menu Type update failed!",
        deleteSucess: "Menu Type deleted successfully!",
        deleteError: "Menu Type delete failed!",
        createSucess: 'Menu Type created successfully!',
        createError: "Menu Type creation failed!",
    },
    MENU_ADD_ONS: {
        url: EndPointsTypes['RESTAURANT_MENU_ADD_ONS_ENDPOINT'],
        queryParams: 'Menu Add Ons',
        updateSucess: "Prerequisite updated successfully!",
        updateError: "Prerequisite update failed!",
        deleteSucess: "Prerequisite deleted successfully!",
        deleteError: "Prerequisite delete failed!",
        createSucess: 'Prerequisite created successfully!',
        createError: "Prerequisite creation failed!",
    },
    MENU_ADD_ONS_OPTIONS: {
        url: EndPointsTypes['RESTAURANT_MENU_ADD_ONS_OPTIONS_ENDPOINT'],
        queryParams: 'Menu Add Ons',
        updateSucess: "Prerequisite Option updated successfully!",
        updateError: "Prerequisite Option update failed!",
        deleteSucess: "Prerequisite Option deleted successfully!",
        deleteError: "Prerequisite Option delete failed!",
        createSucess: 'Prerequisite Option created successfully!',
        createError: "Prerequisite Option creation failed!",
    },
}