import { EndPointsTypes } from "@/common/types/routers/endPoints.types";

export const stockEndPoint = {
    SUPPLIERS: {
        url: EndPointsTypes['STOCK_SUPPLIERS_ENDPOINT'],
        queryParams: 'Suppliers',
        updateSucess: "Suppliers updated successfully!",
        updateError: "Suppliers update failed!",
        deleteSucess: "Suppliers deleted successfully!",
        deleteError: "Suppliers delete failed!",
        createSucess: 'Suppliers created successfully!',
        createError: "Suppliers creation failed!",
    },
    ITEM: {
        url: EndPointsTypes['STOCK_ITEM_ENDPOINT'],
        queryParams: 'Item',
        updateSucess: "Item updated successfully!",
        updateError: "Item update failed!",
        deleteSucess: "Item deleted successfully!",
        deleteError: "Item delete failed!",
        createSucess: 'Item created successfully!',
        createError: "Item creation failed!",
    },
    SUPPLIER_BANK: {
        url: EndPointsTypes['STOCK_SUPPLIER_BANK_ENDPOINT'],
        queryParams: 'SupplierBank',
        updateSucess: "Supplier Bank updated successfully!",
        updateError: "Supplier Bank update failed!",
        deleteSucess: "Supplier Bank deleted successfully!",
        deleteError: "Supplier Bank delete failed!",
        createSucess: 'Supplier Bank created successfully!',
        createError: "Supplier Bank creation failed!",
    },
    SUPPLIER_AUTO_ORDER: {
        url: EndPointsTypes['STOCK_SUPPLIER_AUTO_ORDER_ENDPOINT'],
        queryParams: 'SupplierAutoOrder',
        updateSucess: "Supplier Auto Order updated successfully!",
        updateError: "Supplier Auto Order update failed!",
        deleteSucess: "Supplier Auto Order deleted successfully!",
        deleteError: "Supplier Auto Order delete failed!",
        createSucess: 'Supplier Auto Order created successfully!',
        createError: "Supplier Auto Order creation failed!",
    },
    SUPPLIER_CONTACT: {
        url: EndPointsTypes['STOCK_SUPPLIER_CONTACT_ENDPOINT'],
        queryParams: 'SupplierContact',
        updateSucess: "Supplier Contact updated successfully!",
        updateError: "Supplier Contact update failed!",
        deleteSucess: "Supplier Contact deleted successfully!",
        deleteError: "Supplier Contact delete failed!",
        createSucess: 'Supplier Contact created successfully!',
        createError: "Supplier Contact creation failed!",
    },
}