import { EndPointsTypes } from "@/common/types/routers/endPoints.types";

export const companyEndPoint = {
    AUTH: {
        url: EndPointsTypes['AUTH_ENDPOINT_SIGNUP'],
        queryParams: 'auth',
        updateSucess: "",
        updateError: "",
        deleteSucess: "",
        deleteError: "",
        createSucess: 'User Created successfully!',
        createError: "User creation failed!",
    },
    DETAILS: {
        url: EndPointsTypes['COMPANY_DETAILS_ENDPOINT'],
        queryParams: 'details',
        updateSucess: "Details updated successfully!",
        updateError: "Details update failed!",
        deleteSucess: "Details deleted successfully!",
        deleteError: "Details delete failed!",
        createSucess: 'Details created successfully!',
        createError: "Details creation failed!",
    },
    //todo: change APP_DAYROSTER_ENDPOINT to COMPANY_ROSTER_ENDPOINT but you have to updaet back-end first 
    ROSTER: {
        url: EndPointsTypes['COMPANY_ROSTER_ENDPOINT'],
        queryParams: 'roster',
        updateSucess: "Roster updated successfully!",
        updateError: "Roster update failed!",
        deleteSucess: "Roster deleted successfully!",
        deleteError: "Roster delete failed!",
        createSucess: 'Roster created successfully!',
        createError: "Roster creation failed!",
    },
    ROSTER_TASKS: {
        url: EndPointsTypes['COMPANY_ROSTER_TASKS_ENDPOINT'],
        queryParams: 'roster-tasks',
        updateSucess: "Task updated successfully!",
        updateError: "Task update failed!",
        deleteSucess: "Task deleted successfully!",
        deleteError: "Task delete failed!",
        createSucess: 'Task created successfully!',
        createError: "Task creation failed!",
    },
    HACCP_REPORTS: {
        url: EndPointsTypes['COMPANY_HACCP_REPORTS_ENDPOINT'],
        queryParams: 'haccpReports',
        updateSucess: "HACCP reports updated successfully!",
        updateError: "HACCP reports update failed!",
        deleteSucess: "HACCP reports deleted successfully!",
        deleteError: "HACCP reports delete failed!",
        createSucess: 'HACCP reports created successfully!',
        createError: "HACCP reports creation failed!",
    },
    FORMS: {
        url: EndPointsTypes['COMPANY_FORMS_ENDPOINT'],
        queryParams: 'forms',
        createError: "Form creation failed!",
        updateError: "Form update failed!",
        deleteSucess: "Form deleted successfully!",
        deleteError: "Form delete failed!",
        createSucess: 'Form created successfully!',
        updateSucess: "Form updated successfully!",
    },
    FORM_SECTION: {
        url: EndPointsTypes['COMPANY_FORM_SECTIONS_ENDPOINT'],
        queryParams: 'formSection',
        updateSucess: "Form Section updated successfully!",
        updateError: "Form Section update failed!",
        deleteSucess: "Form Section deleted successfully!",
        deleteError: "Form Section delete failed!",
        createSucess: 'Form Section created successfully!',
        createError: "Form Section creation failed!",
    },
    FORM_DATA: {
        url: EndPointsTypes['COMPANY_FORM_DATA_ENDPOINT'],
        queryParams: 'formData',
        updateSucess: "Files updated successfully!",
        updateError: "Form Data update failed!",
        deleteSucess: "Form Data deleted successfully!",
        deleteError: "Form Data delete failed!",
        createSucess: 'Your Form was submited!',
        createError: "Form Data creation failed!",
    },
    FILES: {
        url: EndPointsTypes['COMPANY_FILES_ENDPOINT'],
        queryParams: 'files',
        updateSucess: "Files updated successfully!",
        updateError: "Files update failed!",
        deleteSucess: "Files deleted successfully!",
        deleteError: "Files delete failed!",
        createSucess: 'Files created successfully!',
        createError: "Files creation failed!",
    },
    REQUESTS: {
        url: EndPointsTypes['COMPANY_REQUESTS_ENDPOINT'],
        queryParams: 'requests',
        updateSucess: "Request updated successfully!",
        updateError: "Request update failed!",
        deleteSucess: "Request deleted successfully!",
        deleteError: "Request delete failed!",
        createSucess: 'Request created successfully!',
        createError: "Request creation failed!",
    },
    ROLES: {
        url: EndPointsTypes['COMPANY_ROLES_ENDPOINT'],
        queryParams: 'roles',
        updateSucess: "Roles updated successfully!",
        updateError: "Roles update failed!",
        deleteSucess: "Roles deleted successfully!",
        deleteError: "Roles delete failed!",
        createSucess: 'Roles created successfully!',
        createError: "Roles creation failed!",
    },
    DEPARTAMENTS: {
        url: EndPointsTypes['COMPANY_DEPARTMENTS_ENDPOINT'],
        queryParams: 'departaments',
        updateSucess: "Departament updated successfully!",
        updateError: "Departament update failed!",
        deleteSucess: "Departament deleted successfully!",
        deleteError: "Departament delete failed!",
        createSucess: 'Departament created successfully!',
        createError: "Departament creation failed!",
    },
    DUTIES: {
        url: EndPointsTypes['COMPANY_DUTIES_ENDPOINT'],
        queryParams: 'duties',
        updateSucess: "Duty updated successfully!",
        updateError: "Duty update failed!",
        deleteSucess: "Duty deleted successfully!",
        deleteError: "Duty delete failed!",
        createSucess: 'Duty created successfully!',
        createError: "Duty creation failed!",
    },
    SHIFTS: {
        url: EndPointsTypes['COMPANY_SHIFTS_ENDPOINT'],
        queryParams: 'shifts',
        updateSucess: "Shift updated successfully!",
        updateError: "Shift update failed!",
        deleteSucess: "Shift deleted successfully!",
        deleteError: "Shift delete failed!",
        createSucess: 'Shift created successfully!',
        createError: "Shift creation failed!",
    },
    TRANSACTIONS: {
        url: EndPointsTypes['COMPANY_TRANSACTIONS_ENDPOINT'],
        queryParams: 'transactions',
        updateSucess: "Transaction updated successfully!",
        updateError: "Transaction update failed!",
        deleteSucess: "Transaction deleted successfully!",
        deleteError: "Transaction delete failed!",
        createSucess: 'Transaction created successfully!',
        createError: "Transaction creation failed!",
    },
    CONTACTS: {
        url: EndPointsTypes['COMPANY_CONTACTS_ENDPOINT'],
        queryParams: 'contacts',
        updateSucess: "Contact updated successfully!",
        updateError: "Contact update failed!",
        deleteSucess: "Contact deleted successfully!",
        deleteError: "Contact delete failed!",
        createSucess: 'Contact created successfully!',
        createError: "Contact creation failed!",
    },
    LINKS: {
        url: EndPointsTypes['COMPANY_LINKS_ENDPOINT'],
        queryParams: 'links',
        updateSucess: "Link updated successfully!",
        updateError: "Link update failed!",
        deleteSucess: "Link deleted successfully!",
        deleteError: "Link delete failed!",
        createSucess: 'Link created successfully!',
        createError: "Link creation failed!",
    },
    DOCUMENTS: {
        url: EndPointsTypes['COMPANY_DOCUMENTS_ENDPOINT'],
        queryParams: 'documents',
        updateSucess: "Document updated successfully!",
        updateError: "Document update failed!",
        deleteSucess: "Document deleted successfully!",
        deleteError: "Document delete failed!",
        createSucess: 'Document created successfully!',
        createError: "Document creation failed!",
    },
    HISTORY: {
        url: EndPointsTypes['SERVICES_HISTORY_ENDPOINT'],
        queryParams: 'history',
        updateSucess: "History updated successfully!",
        updateError: "History update failed!",
        deleteSucess: "History deleted successfully!",
        deleteError: "History delete failed!",
        createSucess: 'History created successfully!',
        createError: "History creation failed!",
    },
    NOTIFICATION: {
        url: EndPointsTypes['SERVICES_NOTIFICATION_ENDPOINT'],
        queryParams: 'notification',
        updateSucess: "Notification updated successfully!",
        updateError: "Notification update failed!",
        deleteSucess: "Notification deleted successfully!",
        deleteError: "Notification delete failed!",
        createSucess: 'Notification created successfully!',
        createError: "Notification creation failed!",
    },
    SMS: {
        url: EndPointsTypes['SERVICES_SMS_ENDPOINT'],
        queryParams: 'sms',
        updateSucess: "SMS updated successfully!",
        updateError: "SMS update failed!",
        deleteSucess: "SMS deleted successfully!",
        deleteError: "SMS delete failed!",
        createSucess: 'SMS created successfully!',
        createError: "SMS creation failed!",
    },
}