import { EndPointsTypes } from "@/common/types/routers/endPoints.types";

export const companyEndPoint = {
    DETAILS: {
        url: EndPointsTypes['COMPANY_DETAILS_ENDPOINT'],
        queryParams: 'details',
        createSucess: "Details created successfully!",
        createError: "Details creation failed!",
        updateSucess: "Details updated successfully!",
        updateError: "Details update failed!",
        deleteSucess: "Details deleted successfully!",
        deleteError: "Details delete failed!",
    },
    //todo: change APP_DAYROSTER_ENDPOINT to COMPANY_ROSTER_ENDPOINT but you have to updaet back-end first 
    ROSTER: {
        url: EndPointsTypes['COMPANY_ROSTER_ENDPOINT'],
        queryParams: 'roster',
        createSucess: "Roster created successfully!",
        createError: "Roster creation failed!",
        updateSucess: "Roster updated successfully!",
        updateError: "Roster update failed!",
        deleteSucess: "Roster deleted successfully!",
        deleteError: "Roster delete failed!",
    },
    HACCP_REPORTS: {
        url: EndPointsTypes['COMPANY_HACCP_REPORTS_ENDPOINT'],
        queryParams: 'haccpReports',
        createSucess: "HACCP reports created successfully!",
        createError: "HACCP reports creation failed!",
        updateSucess: "HACCP reports updated successfully!",
        updateError: "HACCP reports update failed!",
        deleteSucess: "HACCP reports deleted successfully!",
        deleteError: "HACCP reports delete failed!",
    },
    FORMS: {
        url: EndPointsTypes['COMPANY_FORMS_ENDPOINT'],
        queryParams: 'forms',
        createSucess: "Form created successfully!",
        createError: "Form creation failed!",
        updateSucess: "Form updated successfully!",
        updateError: "Form update failed!",
        deleteSucess: "Form deleted successfully!",
        deleteError: "Form delete failed!",
    },
    FORM_SECTION: {
        url: EndPointsTypes['COMPANY_FORM_SECTIONS_ENDPOINT'],
        queryParams: 'formSection',
        createSucess: "Form Section created successfully!",
        createError: "Form Section creation failed!",
        updateSucess: "Form Section updated successfully!",
        updateError: "Form Section update failed!",
        deleteSucess: "Form Section deleted successfully!",
        deleteError: "Form Section delete failed!",
    },
    FORM_DATA: {
        url: EndPointsTypes['COMPANY_FORM_DATA_ENDPOINT'],
        queryParams: 'formData',
        createSucess: "Form Data created successfully!",
        createError: "Form Data creation failed!",
        updateSucess: "Form Data updated successfully!",
        updateError: "Form Data update failed!",
        deleteSucess: "Form Data deleted successfully!",
        deleteError: "Form Data delete failed!",
    }
}